name: lint-wf
on:
  push:
   branches:
    - develop
  pull_request:
    branches:
    - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Htmllint
        run: npm install --save-dev htmllint
      - name: Lint html files
        run: npx htmllint "**/*.html"
     
     # run: npm install --save-dev stylelint

     # run: npx stylelint "**/*.css"
      - name: Display package.json content
        run:  cat package.json
        


